### ISSUE TITLE
Properties Panel Extension throws error

### ISSUE THREAD

**Issue by rashedbayani** [bpmn-io/bpmn-js-examples#137]
__Describe the Bug__

When trying to to add a new tab to the existing Camunda properties panel like the example, an error will be shown in console:
Properties provider does not impement #getTabs(element) API

__Steps to Reproduce__

if you try to run the example for properties panel extension, you'll see the error. it seems that the problem occurs because the provider is adding the getTabs only after the provider was registered, therefore it throws an error because the function is not defined at this time.

1. do this
2. do that
3. now this happens

__Expected Behavior__

expected to be able to add a custom tab to the properties panel.

__Environment__

I've tried it in my Angular project. But it doesn't work in javascript either

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

---

Initially reported via [forum](https://forum.bpmn.io/t/properties-panel-extension-throwing-error/6867).

**Comment by nikku** [comment]
Please link the example you're referring to. 

The method clearly indicates that a properties provider must implement a `#getTabs(element)` method. Which API does the provider implement instead?

**Comment by pinussilvestrus** [comment]
Some context that was not added to the issue description: https://forum.bpmn.io/t/properties-panel-extension-throwing-error/6867

**Comment by nikku** [comment]
Thanks for providing the context @pinussilvestrus.

To summarize the root cause of this issue:

* We've added strict validation in the properties panel to ensure that providers offer the needed API at _registration time_
* Our example promotes a usage pattern that sets up the needed API _after registration_

My proposal is that we update the example to reflect the new, safe usage pattern.
