### ISSUE TITLE
Add a more simple example

### ISSUE THREAD

**Issue by wsteven24** [bpmn-io/bpmn-js-examples#226]
Could you please elaborate a simple example of how to add a custom property panel? The current one is too complex and I don't get its purpose.

**Comment by wsochoa** [comment]
I'm trying to extend from `bpmn-js-properties-panel`. I've followed a few tutorials from different websites, all are quite different because of libs versions. For instance, this one doesn't work on newer versions: https://codesandbox.io/s/magic-properties-provider-dufw1?file=/src/provider/SpellProps.js

This one is old as well and seems to not work with newer libs: https://camunda.com/blog/2017/04/adding-custom-elements-to-bpmn-properties-panel/

The previous one points to: https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension
which is the one I'm trying right now. Unfortunately, I'm getting an error:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'context')`

The error occurs in this line of code:
`const modeling = useService('modeling');`

I hope you understand my struggle, there's a need to keep tutorials as simple as possible and more organized as now they are spread and are not backward compatible as new libraries are delivered

**Comment by wsteven24** [comment]
I'm closing this issue. Will post another one with the error I'm facing right now
