### ISSUE TITLE
Properties Panel Extension: how to add entryFactory.table?

### ISSUE THREAD

**Issue by rbajaniya** [bpmn-io/bpmn-js-examples#43]
I have used 
```
group.entries.push(entryFactory.table({
      id: 'newTable',
      labels: ['Name', 'Value'],
      addLabel: 'Add Entry',
      modelProperties: ['key', 'value']
    }));
```
but this is not working.

**Comment by nikku** [comment]
Please checkout [`TableEntryFactory`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/factory/TableEntryFactory.js) as well as its [usages in the code base](https://github.com/bpmn-io/bpmn-js-properties-panel/search?utf8=%E2%9C%93&q=entryFactory.table&type=).

**Comment by samuelj2r** [comment]
I'm blocked in the same problem. It would be appreciated a less generic response. Maybe some example or help keeping in mind that not all of us have a high knowledge of the use of these libraries.

**Comment by nikku** [comment]
@samuelj2r What exactly is generic in my previous answer? Do you got a specific question regarding existing usages in our code base? What did you try? Where did you get stuck.

Share exactly where you got stuck and we are happy to help.

**Comment by samuelj2r** [comment]
Thanks @nikku  for you quick answer. I'm sorry if it sounded rude. I had followed your two links to see both the code and the usages. The problem that I am facing is that, us much as I can see and try to read the code, there is no documentation about it. Because of that I am finding really hard to understand raw code.  On the other hand, I have put my hope on the code usages that you posted, however they all belongs to the properties panel examples witch are really hard to adapt. 

In any case, just in case you can show me the light: I am traying to create my our property panel. To do so, I have downloaded and played with the proyect linked here https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension. In it, there is a readme witch explains how to add properties and handle tabs for specifics elements. So far so good. Now, what I need is to create a table property for tasks elements to handle inputs/outputs (just like camunda properties does but without the rest of the elements that cames with the camunda properties examples). it would be great to have something similar to the readme that i am linking to have a better view of how to attach that specific property to one specific element. I mean, i am not asking to write handred of lines to help, just can you point my out the steps to create a basic example of that property linked to a task element for example. No need to enter deeper details just pointing where the table is declared, how it is linked to the element, where to specific the properties of it... It would be really apreciated.

**Comment by nikku** [comment]
The [`InputOutputParameter`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/2568265384484c2fd18fad70a9c17e5c44f15941/lib/provider/camunda/parts/implementation/InputOutputParameter.js) implementation may be valuable for you. It implements the input / output handling.

I suggest you to debug the existing implementation (`F12` in your browser) to understand what is going on there.

**Comment by samuelj2r** [comment]
Sure! I was doing exacly that at the moment.  But how to atach that in my proyect? Confirm me this if possible:

Do i need to:

1º Extract the code in InputOutputParameter (part folder) and put it on my proyect
2º Create my own PropertiesProvider.js
3º Declare it on my index.js of the whole proyect
4º Create the descriptor?

**Comment by nikku** [comment]
This is exactly what you need to do.

**Comment by nikku** [comment]
You must pass the `bpmnFactory`; it is used to create elements if you press the `+` button.

Get it in the same way you retrieve the `elementRegistry`.

**Comment by samuelj2r** [comment]
Knowing that it should be easy but I cant follow the trace to the moment where the elementRegistry is set.

Trace:
On my Provider --> export default function MagicPropertiesProvider(
    eventBus, bpmnFactory, elementRegistry,
    translate) {


On my index.js of the provider --> `import MagicPropertiesProvider from './MagicPropertiesProvider';

export default {
  __init__: [ 'propertiesProvider' ],
  propertiesProvider: [ 'type', MagicPropertiesProvider ]
};`

on my general Index.js

`import propertiesProviderModule from './provider/customProperties';`

so, where is the elementRegistry retrieved? also I guest i have to use as bpmnFactory for my inputoutput one of these https://github.com/bpmn-io/bpmn-js-properties-panel/tree/2568265384484c2fd18fad70a9c17e5c44f15941/lib/factory but witch one?

**Comment by samuelj2r** [comment]
any idea @nikku?

**Comment by nikku** [comment]
The [`BpmnFactory`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/BpmnFactory.js) is part of bpmn-js and gets exposed once you load the `bpmn-js/lib/features/modeling` module.

The [`BpmnModeler`](https://github.com/bpmn-io/bpmn-js-examples/blob/master/properties-panel-extension/app/index.js#L17), per default ships with this module.

**Comment by samuelj2r** [comment]
Hi @nikku, I have tried not to bother you this days but I am still fighting to create the inputs/outpus...

I thing I have solved the problem with the bpmnFactory and it is now being passed. Still, solved one problem but comes the next:

![image](https://user-images.githubusercontent.com/18597483/41226064-a17730b2-6d70-11e8-8722-d71610d7e591.png)

Could you  give me a hand on this?
